# Generated by Django 2.1.2 on 2018-10-25 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_auto_20181023_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='media\no_image.jpeg', upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('price', models.FloatField(default=0.0)),
                ('created', models.DateTimeField(auto_now=True)),
                ('ranking', models.DecimalField(decimal_places=0, default=0, max_digits=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=18)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Good')),
            ],
        ),
        migrations.RemoveField(
            model_name='goods',
            name='category',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='media\no_image.jpeg', upload_to=''),
        ),
        migrations.DeleteModel(
            name='Goods',
        ),
        migrations.AddField(
            model_name='good',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.Category'),
        ),
    ]
