# Generated by Django 2.1.2 on 2018-10-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_auto_20181025_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='media/no_image.jpeg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='good',
            name='image',
            field=models.ImageField(default='media/no_image.jpeg', upload_to=''),
        ),
    ]
