# Generated by Django 2.1.2 on 2018-10-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0007_auto_20181025_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='no_image.jpeg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='good',
            name='image',
            field=models.ImageField(default='no_image.jpeg', upload_to=''),
        ),
    ]
